# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Function Deployment - wed-funcs

on:
  push:
    branches:
    - master
    paths:
    - "src/api/**"
    - ".github/workflows/azure-wed-functions.yml"
  workflow_dispatch:


env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/api/Function' # set this to the path to your web app project, defaults to the repository root
  AZURE_FUNCTIONAPP_TEST_PATH: 'src/api/Function.Tests' # set this to the path to your web app test project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Unit Tests'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_TEST_PATH }}'
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
        popd

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3EA0CBC09A174874B0DC9AF4F415FF85 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F54E685E0E474CE69F3FEFD8159440CC }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F509572AA85347CDA285C4C8A867B678 }}

    - name: 'Set Azure Function App Settings'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set \
            --name wed-web \
            --resource-group wed-web \
            --settings \
              "RsvpOptions__InviteCode=${{ secrets.RSVP_INVITE_CODE }}" \
              "RsvpOptions__AllowedHosts__0=laura-und.marvin-stue.de" \
              "RsvpOptions__AllowedHosts__1=localhost:7234" \
              "RsvpOptions__AllowedHosts__2=wedding-website.azurewebsites.net" \
              "RsvpOptions__AllowedHosts__3=wed-web.azurewebsites.net" \
              "RegistrationsOptions__QueryCode=${{ secrets.REGISTRATION_QUERY_CODE }}" \
              "CosmosDbOptions__ConnectionString=${{ secrets.COSMOSDB_CONNECTION_STRING }}" \
              "CosmosDbOptions__TableName=${{ secrets.COSMOSDB_TABLE_NAME }}" \
              "TurnstileOptions__SecretKey=${{ secrets.TURNSTILE_SECRET_KEY }}"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'wed-web'
        slot-name: 'Production'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
